export const navigations = [
  { name: 'Classroom', path: '/classroom', icon: 'class', who: 0 },
  { name: 'Join new classroom', path: '/newclassroom', icon: 'school', who: 0 },
  { name: 'Dashboard', path: '/dashboard/default', icon: 'dashboard', who: 0 },
  { name: 'Classes', path: '/teacher/dashboard', icon: 'class', who: 1 },
  { name: 'Classroom', path: '/teacher/classroom', icon: 'school', who: 1 },
  { name: 'student', path: '/admin/student', icon: 'person', who: 2 },
  { name: 'teacher', path: '/admin/teacher', icon: 'person', who: 2 },
  { name: 'classroom', path: '/admin/classroom', icon: 'school', who: 2 },
  { name: 'Teacher credit', path: '/admin/teacher/update', icon: 'add', who: 2 },
  { name: 'student', path: '/superadmin/student', icon: 'person', who: 3 },
  { name: 'teacher', path: '/superadmin/teacher', icon: 'person', who: 3 },
  { name: 'admin', path: '/superadmin/admin', icon: 'person', who: 3 },
  { name: 'Create admin', path: '/superadmin/admincreate', icon: 'addperson', who: 3 },

  // { label: 'PAGES', type: 'label' },
  // {
  //   name: 'Session/Auth',
  //   icon: 'security',
  //   children: [
  //     { name: 'Sign in', iconText: 'SI', path: '/session/signin' },
  //     { name: 'Sign up', iconText: 'SU', path: '/session/signup' },
  //     { name: 'Forgot Password', iconText: 'FP', path: '/session/forgot-password' },
  //     { name: 'Error', iconText: '404', path: '/session/404' },
  //   ],
  // },
  // { label: 'Components', type: 'label' },
  // {
  //   name: 'Components',
  //   icon: 'favorite',
  //   badge: { value: '30+', color: 'secondary' },
  //   children: [
  //     { name: 'Auto Complete', path: '/material/autocomplete', iconText: 'A' },
  //     { name: 'Buttons', path: '/material/buttons', iconText: 'B' },
  //     { name: 'Checkbox', path: '/material/checkbox', iconText: 'C' },
  //     { name: 'Dialog', path: '/material/dialog', iconText: 'D' },
  //     { name: 'Expansion Panel', path: '/material/expansion-panel', iconText: 'E' },
  //     { name: 'Form', path: '/material/form', iconText: 'F' },
  //     { name: 'Icons', path: '/material/icons', iconText: 'I' },
  //     { name: 'Menu', path: '/material/menu', iconText: 'M' },
  //     { name: 'Progress', path: '/material/progress', iconText: 'P' },
  //     { name: 'Radio', path: '/material/radio', iconText: 'R' },
  //     { name: 'Switch', path: '/material/switch', iconText: 'S' },
  //     { name: 'Slider', path: '/material/slider', iconText: 'S' },
  //     { name: 'Snackbar', path: '/material/snackbar', iconText: 'S' },
  //     { name: 'Table', path: '/material/table', iconText: 'T' },
  //   ],
  // },
  // {
  //   name: 'Charts',
  //   icon: 'trending_up',
  //   children: [{ name: 'Echarts', path: '/charts/echarts', iconText: 'E' }],
  // },
  // {
  //   name: 'Documentation',
  //   icon: 'launch',
  //   type: 'extLink',
  //   path: 'http://demos.ui-lib.com/matx-react-doc/',
  // },
];
